### ISSUE TITLE
Shaded netty does not work with epoll activated

### ISSUE THREAD

**Issue by NicoK** [apache/flink-shaded#30]
If epoll is activated via the (undocumented) `taskmanager.network.netty.transport: epoll` configuration option, the netty stack will crash with
```
2017-12-19 11:45:53,859 ERROR org.apache.flink.runtime.taskmanager.TaskManager              - Error while starting up taskManager
java.lang.NoClassDefFoundError: io/netty/util/NetUtil
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.apache.flink.shaded.netty4.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193)
	at org.apache.flink.shaded.netty4.io.netty.channel.epoll.Native.<clinit>(Native.java:49)
	at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventArray.<clinit>(EpollEventArray.java:40)
	at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:65)
	at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:76)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at org.apache.flink.shaded.netty4.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61)
	at org.apache.flink.shaded.netty4.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:49)
	at org.apache.flink.runtime.io.network.netty.NettyClient.initEpollBootstrap(NettyClient.java:160)
	at org.apache.flink.runtime.io.network.netty.NettyClient.init(NettyClient.java:80)
	at org.apache.flink.runtime.io.network.netty.NettyConnectionManager.start(NettyConnectionManager.java:52)
	at org.apache.flink.runtime.io.network.NetworkEnvironment.start(NetworkEnvironment.java:289)
	at org.apache.flink.runtime.taskexecutor.TaskManagerServices.fromConfiguration(TaskManagerServices.java:160)
	at org.apache.flink.runtime.taskmanager.TaskManager$.startTaskManagerComponentsAndActor(TaskManager.scala:2003)
	at org.apache.flink.runtime.taskmanager.TaskManager$.runTaskManager(TaskManager.scala:1832)
	at org.apache.flink.runtime.taskmanager.TaskManager$$anonfun$1.apply$mcV$sp(TaskManager.scala:1944)
	at org.apache.flink.runtime.taskmanager.TaskManager$$anonfun$1.apply(TaskManager.scala:1922)
	at org.apache.flink.runtime.taskmanager.TaskManager$$anonfun$1.apply(TaskManager.scala:1922)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.flink.runtime.akka.AkkaUtils$.retryOnBindException(AkkaUtils.scala:759)
	at org.apache.flink.runtime.taskmanager.TaskManager$.runTaskManager(TaskManager.scala:1922)
	at org.apache.flink.runtime.taskmanager.TaskManager$.selectNetworkInterfaceAndRunTaskManager(TaskManager.scala:1691)
	at org.apache.flink.runtime.taskmanager.TaskManager$$anon$2.call(TaskManager.scala:1592)
	at org.apache.flink.runtime.taskmanager.TaskManager$$anon$2.call(TaskManager.scala:1590)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.runtime.taskmanager.TaskManager$.main(TaskManager.scala:1590)
	at org.apache.flink.runtime.taskmanager.TaskManager.main(TaskManager.scala)
Caused by: java.lang.ClassNotFoundException: io.netty.util.NetUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
```

The cause is `libnetty-transport-native-epoll.so` not being aligned with the shaded namespace and we can fix this as described in https://github.com/netty/netty/issues/6665 and https://github.com/netty/netty/commit/075a54af3e607c20eeaf7809a2a08602abd5d735:
- `System.setProperty("io.netty.packagePrefix", "org.apache.flink.shaded.");` inside projects using  `flink-shaded`
- rename `META-INF/native/libnetty-transport-native-epoll.so` to  `META-INF/native/liborg-apache-flink-shaded-netty-transport-native-epoll.so`

**Comment by zentol** [comment]
Would there be side-effects if we were to always set this property?

**Comment by zentol** [comment]
https://github.com/netty/netty/commit/075a54af3e607c20eeaf7809a2a08602abd5d735 was unfortunately only merged to the 4.1 version of netty so there's nothing we can do until we upgrade our dependency.

**Comment by NicoK** [comment]
ok, thanks for having a second look at it - let's keep this in mind for the next upgrade then

**Comment by zentol** [comment]
oh I didn't consider that. hmm. Sooo....that either means a fork where we rename the system property, or we try to modify it with the shade-plugin by relocation "io.netty.packagePrefix".

**Comment by NicoK** [comment]
yes, maybe it is even relocated already - we need to make sure though and then set the relocated system property correctly

**Comment by makeyang** [comment]
all:
in order to use epoll, is it require linux kernel version is 4.0.16 or not?//base on Native transports doc in this link:http://netty.io/wiki/native-transports.html

**Comment by NicoK** [comment]
No, that seems to be the netty version - but in order to use our shaded netty with epoll, we would need to set Flink's dependency to Netty 4.1 as noted by @zentol above. That is something we're aiming for after Flink 1.5.

**Comment by zentol** [comment]
Fixed in 149cec8fc3ffdcc8ef080533ea0a9ee33ee008a3

**Comment by AlexDag** [comment]
My Flink 1.11.1 say me on starting job :DEBUG org.apache.flink.shaded.netty4.io.netty.util.internal.NativeLibraryLoader [] - Unable to load the library 'org_apache_flink_shaded_netty4_netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no org_apache_flink_shaded_netty4_netty_transport_native_epoll_x86_64 in java.library.path
What could be happened ?

**Comment by tillrohrmann** [comment]
Did the other loading mechanism load the library? Maybe you could share the complete logs with us.

**Comment by AlexDag** [comment]
Hi Roman, Till,
sorry to bother you, I wanted to notify you about : finally , I've
successfully run today my Apache Flink.
My solution was:
1. Download Apache Flink *1.10.2*
2. Nothing changing  on my VMs nodes.
3. Run ./bin/start-cluster.sh
4. Run WordCount.jar
It's all.
It would be great to find a solution for Apache Flink 1.11.*.

Best Regards
Alex
